### ISSUE TITLE
No dll file?

### ISSUE THREAD

**Issue by 280373808** [FairBear/HS2_PovX#1]
Sorry but after downloading this I can't seem to find the dll file. 
Sorry for being an idiot if I'm doing this wrong. :(

**Comment by MrPotato435** [comment]
Looks like you downloaded the master file. You should download it in the release.
[https://github.com/FairBear/HS2_PovX/releases](url)

**Comment by edengate25** [comment]
I'm also getting this issue and the link you put doesn't work. :(

**Comment by BrandonCLockon** [comment]
Releases is empty for me, only the master file can be downloaded in this thread

**Comment by octopusxiang** [comment]
looks like I am more of an idiot...

**Comment by octopusxiang** [comment]
I click on the link but it says there is no such file

**Comment by FairBear** [comment]
![image](https://user-images.githubusercontent.com/49444689/95793679-b317f500-0d18-11eb-9e8a-e22060cb2cf3.png)
